config/routes.rb
Echidna::Application.routes.draw do

  get '/jobs/:id/status', to: 'jobs#status'

  authenticated :user do
    root to: 'panels#index'
    post 'add_stopword' => 'users#add_stopword'

    resources :panels do
      member do
        get :trends
        get :tweets
        put :update_period
      end
    end

    resources :people do
      collection do
        get :stats
      end
    end

    resources :tweets, only: [] do
      member do
        post :spam
        post :spam_user
      end
    end
  end

  root to: 'home#index'
  devise_for :users
  resources :users

  authenticated :user do
    require 'sidekiq/web'
    require 'sidekiq_status/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :tencent do
    resources :agents, only: [:new, :index] do
      get 'callback', on: :collection
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController

  def new
    redirect_to TencentAgent.weibo_client.auth_code.authorize_url
  end

  def callback
    begin
      TencentAgent.create(TencentAgent.weibo_client.auth_code.get_token(params[:code]).to_hash.symbolize_keys)
      render json: {success: true}
    rescue => e
      render json: {success: false, error: e.message}
    end
  end

end

app/controllers/tencent/agents_controller.rb
class Tencent::AgentsController < InheritedResources::Base
  def new
    redirect_to TencentAgent.weibo_client.auth_code.authorize_url
  end

  def callback
    begin
      token = TencentAgent.weibo_client.auth_code.get_token(params[:code]).to_hash.symbolize_keys
      agent = TencentAgent.find_or_initialize_by(name: token[:name])
      agent.update_attributes(token)
      render json: {success: true}
    rescue => e
      render json: {success: false, error: e.message}
    end
  end
end

app/views/tencent/agents/index.html.slim
h3 Tencent agents

= link_to 'Add new Tencent agent', new_tencent_agent_path

.row
  .span8
    - collection.each do |tecent_agent|
      table.table.table-bordered.table-striped
        caption
          h4= tecent_agent.name
        thead
          th.id List ID
          th.name List name
          th.members List members
          th.time Timestamp of latest known tweet
        tbody
          - tecent_agent.tencent_lists.each do |list|
            tr
              td= list.list_id
              td= list.name
              td= list.member_count
              td= list.latest_tweet_timestamp