config/routes.rb
Echidna::Application.routes.draw do

  get '/jobs/:id/status', to: 'jobs#status'

  authenticated :user do
    root to: 'panels#index'
    post 'add_stopword' => 'users#add_stopword'

    resources :panels do
      member do
        get :trends
        get :tweets
        put :update_period
      end
    end

    resources :people do
      collection do
        get :stats
      end
    end

    resources :tweets, only: [] do
      member do
        post :spam
        post :spam_user
      end
    end
  end

  root to: 'home#index'
  devise_for :users
  resources :users

  authenticated :user do
    require 'sidekiq/web'
    require 'sidekiq_status/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :tencent do
    resources :agents, only: [:new, :index] do
      get 'callback', on: :collection
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/panel.rb
class Panel
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name
  field :age_ranges, type: Array
  field :gender
  field :period
  field :freq_limit, type: Integer

  validates :name, presence: true

  belongs_to :user, index: true
  has_and_belongs_to_many :cities
  has_and_belongs_to_many :groups

  before_save :remove_empty_age_range, :set_groups

  index({ user_id: 1, created_at: -1 })

  def start_years
    self.age_ranges.map { |age_range| age_range.split(' - ').first }
  end

  def end_years
    self.age_ranges.map { |age_range| age_range.split(' - ').last }
  end

  def age_ranges_label
    case age_ranges
    when []
      'Age all'
    else
      age_ranges.map do |age_range|
        age_range == '0 - 0' ? 'Age unknown' : age_range
      end.join(', ')
    end
  end

  def gender_label
    case gender
    when 'unknown'
      'Gender unknown'
    when ''
      'Gender all'
    else
      gender
    end
  end

  def cities_label
    case cities
    when []
      'City all'
    else
      cities.map(&:label).join(', ')
    end
  end

  private
  def remove_empty_age_range
    self.age_ranges.reject! { |age_range| age_range.blank? }
  end

  def set_groups
    self.group_ids = Group.all_for_panel(self).map(&:id)
  end
end

app/controllers/panels_controller.rb
class PanelsController < InheritedResources::Base
  respond_to :html, :json

  def create
    create! { root_url }
  end

  def update
    update! { root_url }
  end

  def update_period
    resource.update_attribute :period, params[:period]
    render json: {}
  end

  def trends
    length, period = parse_period(params[:period])
    @job_id = TrendsWorker.perform_async(params[:id], current_user.id.to_s, length, period)
    respond_to do |format|
      format.json { render json: {job_id: @job_id} }
    end
  end

  def tweets
    length, period = parse_period(params[:period])
    @job_id = TweetsWorker.perform_async(params[:id], params[:word], length, period)
    respond_to do |format|
      format.json { render json: {job_id: @job_id} }
    end
  end

protected
  def begin_of_association_chain
    current_user
  end

  def parse_period(period)
    case period
    when "month"
      [30, "days"]
    when "week"
      [7, "days"]
    when "day"
      [24, "hours"]
    else
      [7, "hours"]
    end
  end
end

app/helpers/panels_helper.rb
module PanelsHelper
  def current_period
    "1 " + (params[:period] || "day")
  end

  def cities_options_for_select
    City.all.map {|city| [city.name, city.id] }
  end

  def age_ranges_options_for_select
    Person::BIRTH_YEARS.map do |birth_year|
      if birth_year.first == Person::BIRTH_YEAR_UNKNOWN
        ['Unknown', "#{birth_year.first} - #{birth_year.last}"]
      else
        ["#{birth_year.first} - #{birth_year.last}", "#{birth_year.first} - #{birth_year.last}"]
      end
    end
  end

  def gender_options_for_select
    Person::GENDERS.map { |gender| [gender, gender] }
  end
end

app/views/panels/_form.html.slim
= simple_form_for panel, html: {class: 'form-horizontal'} do |f|
  = f.input :name
  = f.input :city_ids, collection: cities_options_for_select, include_blank: 'All', input_html: {multiple: true, size: 10}
  = f.input :age_ranges, collection: age_ranges_options_for_select, include_blank: 'All', input_html: {multiple: true, size: 10}
  = f.input :gender, collection: gender_options_for_select, include_blank: 'All'
  = f.button :submit

app/views/panels/_links.html.slim
- current_user.panels.each do |panel|
  p
    = link_to "Panel: #{panel.name}", trends_panel_path(panel)
    = link_to "Edit", edit_panel_path(panel), class: 'btn'

app/views/panels/edit.html.slim
h3 Edit panel

= render 'form', panel: @panel

app/views/panels/index.html.slim
h2 Panels

= link_to 'New Panel', new_panel_path, class: 'btn btn-primary new-panel-btn'

.tabbable
  ul.nav.nav-tabs.panels-tabs
    - @panels.each_with_index do |panel, index|
      li class=(index == 0 ? "active" : "")
        = link_to panel.name, "#panel-#{panel.id}", "data-toggle" => "tab"
  .tab-content
    - @panels.each_with_index do |panel, index|
      div class=(index == 0 ? "tab-pane active" : "tab-pane") id="panel-#{panel.id}"
        .panel data-panel-id=panel.id data-panel-period=(panel.period || "day")
          .header
            .info
              span.cities.label.label-info= panel.cities_label
              span.ages.label.label-info= panel.age_ranges_label
              span.gender.label.label-info= panel.gender_label
            /.check-live
              /input.live type='checkbox' name='live'
              /label for='live' Live
            .spinner
            .commands
              = link_to 'Edit', edit_panel_path(panel), class: 'btn btn-primary'
              = link_to 'Delete', panel_path(panel), method: :delete, class: 'btn btn-danger', confirm: 'Are you sure to delete?'
            .navbar
              ul.nav.nav-pills.periods
                li= link_to '1 month', '#', "data-period" => "month"
                li= link_to '1 week', '#', "data-period" => "week"
                li= link_to '1 day', '#', "data-period" => "day"
              form.navbar-search
                .input-prepend
                  span.add-on Freq limit
                  input.freq-limit.input-small type='text' value=panel.freq_limit
          .body
            .trends
            .tweets

#history-stats-chart

app/views/panels/new.html.slim
h3 New panel

= render 'form', panel: @panel

app/views/panels/trends.html.slim
= link_to 'New panel', new_panel_path

= render 'links'

h3 Trends for panel #{@panel} #{current_period}

.periods
  = link_to '1 month', period: 'month'
  = link_to '1 week', period: 'week'
  = link_to '1 day', period: 'day'

.live
  input type='checkbox' name='live' id='live'
  label for='live' Live
.spinner

.clear

#trends_job_id.hide data-job-id=@job_id
#trends
#tweets