config/routes.rb
Echidna::Application.routes.draw do

  get '/jobs/:id/status', to: 'jobs#status'

  authenticated :user do
    root to: 'panels#index'
    post 'add_stopword' => 'users#add_stopword'

    resources :panels do
      member do
        get :trends
        get :tweets
        put :update_period
      end
    end

    resources :people do
      collection do
        get :stats
      end
    end

    resources :tweets, only: [] do
      member do
        post :spam
        post :spam_user
      end
    end
  end

  root to: 'home#index'
  devise_for :users
  resources :users

  authenticated :user do
    require 'sidekiq/web'
    require 'sidekiq_status/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :tencent do
    resources :agents, only: [:new, :index] do
      get 'callback', on: :collection
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/views/layouts/_header.html.slim
.navbar-inner
  .container
    = link_to "Trends", root_path, class: 'brand'
    .container.nav-collapse
      ul.nav
        - if user_signed_in?
          li= link_to 'People stats', stats_people_path
          li= link_to 'Tencent agents', tencent_agents_path
          li= link_to 'Edit account', edit_user_registration_path
        - else
          li= link_to 'Sign up', new_user_registration_path

        - if user_signed_in?
          li= link_to 'Sign out', destroy_user_session_path, method: 'delete'
        - else
          li= link_to 'Sign in', new_user_session_path

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Trends"
    = csrf_meta_tags

    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"

    = stylesheet_link_tag "application", media: "all"

    /= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '144x144'
    /= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '114x114'
    /= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '72x72'
    /= favicon_link_tag 'images/apple-touch-icon-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png'
    /= favicon_link_tag 'favicon.ico', rel: 'shortcut icon'

  body
    .navbar.navbar-fixed-top= render 'layouts/header'

    .container
      .row
        .span12
          = bootstrap_flash
          = yield

      footer
        p &copy; Transist 2013

    = javascript_include_tag '//www.google.com/jsapi'
    = javascript_include_tag "application"